### ISSUE TITLE
ANgst Folder is not created

### ISSUE THREAD

**Issue by jaresoles** [moshi4/FastDTLmapper#65]
Need help with this please. Why doesnt the angst folder form?
I dont understand what might have caused this as I only ran the default command.

Thank you!

![image](https://user-images.githubusercontent.com/69087097/182052085-befd9cd0-24ae-4e7a-a085-152d1e7eb6ba.png)

**Comment by moshi4** [comment]
I assume you have installed and run FastDTLmapper in Anaconda's Python 3.9 environment.
Since AnGST only works in a Python 2.X environment, I assume you are getting an error at runtime on Anaconda where Python 2.X and Python 3.X cannot coexist.

It is a little troublesome, but in order to run FastDTLmapper, it is necessary to install it in an environment where Python 2.X and Python 3.X coexist, such as Ubuntu 20.04, without using Anaconda.
